// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillSync.Infrastructure.Persistence;

#nullable disable

namespace SkillSync.Infrastructure.Migrations
{
    [DbContext(typeof(SkillSyncDbContext))]
    [Migration("20251020140302_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SkillSync.Domain.Entities.JobPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobPosts", (string)null);
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JobPostId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPracticed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.Skill", b =>
                {
                    b.HasOne("SkillSync.Domain.Entities.JobPost", null)
                        .WithMany("RequiredSkills")
                        .HasForeignKey("JobPostId");
                });

            modelBuilder.Entity("SkillSync.Domain.Entities.JobPost", b =>
                {
                    b.Navigation("RequiredSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
